### ISSUE TITLE
Support Speech Recognition

### ISSUE THREAD

**Issue by endeffects** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#1]
Is it possible to support speech recognation also?
https://tutorialzine.com/2017/08/converting-from-speech-to-text-with-javascript

**Comment by jsakamoto** [comment]
Thank you for your suggestion!

Ok, I'll try to create a wrapper library for Blazor to support Speech Recognition API.

However, I'm busy until after July of this year,  
I'll try to build alpha version in May, but I can't promise it.

Could you wait for it?

**Comment by jsakamoto** [comment]
See also: https://twitter.com/jsakamoto/status/1123387451882389504

**Comment by endeffects** [comment]
Thanks, i hope you‘ll be successfully. :)

**Comment by jsakamoto** [comment]
I started creating SpeechRecognition API support library for Blazor.

- **GitHub repository:** https://github.com/jsakamoto/Toolbelt.Blazor.SpeechRecognition
- **NuGet package:** https://www.nuget.org/packages/Toolbelt.Blazor.SpeechRecognition/

Please remember, It is very early prototype version, therefore, it hasn't document comment, it might be buggy, it might have breaking-changes in the future.

**Comment by endeffects** [comment]
Wow cool, i'll try it out :)

**Comment by endeffects** [comment]
works really nice! thanks again :)
