### ISSUE TITLE
Support for SSML?

### ISSUE THREAD

**Issue by drtrifle** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#15]
Hi, I was wondering if this project supports Speech Synthesis Markup Language (SSML)
For Kanji characters, there may be more than one reading for a character (生 can be なま or せい, etc) and I want to be able to have it use the intended pronunciation.
I've tried it on the live site and it doesn't seem to be supported but I was wondering if I maybe just got the syntax wrong
Anways, thanks so much for your work on this! 
I'm currently using it on my own Blazor Project and it works really well :)

**Comment by jsakamoto** [comment]
@drtrifle 
Thank you for your proposal. The SSML support is interesting. Technicaly, the SSML supporting feature should be better to make an individual NuGet package with dependency on this NuGet package, I think. Unfortunately, I haven't had enough time to create new features on this package recently 😥. So, I hope somebody could create an SSML-supporting supplement library.

**Comment by drtrifle** [comment]
@jsakamoto 
Ah I see, that's too bad then.
Thanks for reading my suggestion anyway
