### ISSUE TITLE
strange problem: works pefrect on my dev machine - but not once deployed to Azure App Service

### ISSUE THREAD

**Issue by hjrb** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#16]
Issue: enumerating voices works fine. But trying to use the selected voice it will always use the default en voice.
Same test on my dev PC - works.
Platform: Blazor WASM, .NET 8
I tested in Edge, FF and Chrome - always the same behaviour.

**Comment by hjrb** [comment]
I want to add something. When I set the Lang parameter in the SpeechSynthesisUtterance is will then use the default voice for that language. I assume something with resolving the Uri of the voice does not work.  To test you will need to deploy to a real website 0 - localhost.

**Comment by jsakamoto** [comment]
@hjrb, I'd really appreciate it if you could provide a sample project to reproduce the problem that you mentioned. Thank you in advance for your cooperation!

**Comment by jsakamoto** [comment]
@hjrb I figured out the reason for the problem you reported.

It does not depend on the location of the app. The issue has been based on what properties are touched in the application code.

I fixed this issue and published the new version of this package.

https://www.nuget.org/packages/Toolbelt.Blazor.SpeechSynthesis/10.3.1#releasenotes-body-tab

Could you try it out?

Thank you for your reporting and cooperation! 👍

**Comment by hjrb** [comment]
updated, recompiled, deployed => issue fixed! thanks a lot!! 👍👌😊
