### ISSUE TITLE
Server and Signal-R version

### ISSUE THREAD

**Issue by gp2-gp2** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#2]
Hi, is this also supposed to work with server side blazor app?
So far I was not able to make it working in latest 3.1 .net core server side blazor template.

**Comment by jsakamoto** [comment]
Thank you for head up me!

I added support for Server-Side Blazor on .NET Core 3.1 at "Blazor Speech Synthesis" ver.8.0!

- https://www.nuget.org/packages/Toolbelt.Blazor.SpeechSynthesis/8.0.0

**Comment by gp2-gp2** [comment]
> Thank you for head up me!
> 
> I added support for Server-Side Blazor on .NET Core 3.1 at "Blazor Speech Synthesis" ver.8.0!
> 
> * https://www.nuget.org/packages/Toolbelt.Blazor.SpeechSynthesis/8.0.0

Thanks! It works like a charm!
