### ISSUE TITLE
.NET 5.0 is not yet supported?

### ISSUE THREAD

**Issue by bestpika** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#4]
Today I tried to update the target framework to .NET 5.0 and then compiled it and it didn't work.

**Comment by jsakamoto** [comment]
It will be works fine even on .NET 5.

see also my sample site: https://github.com/jsakamoto/Toolbelt.Blazor.SpeechSynthesis/commit/c9128483ed0a96611e89c44a90475f90c75de180

**Comment by bestpika** [comment]
Oh, sorry.
I mean the NuGet's package.

**Comment by bestpika** [comment]
@jsakamoto I find that changing `<app>` to `<div id="app">` breaks the whole layout of the site, and changing it to `<app id="app">` should be a better solution.

**Comment by jsakamoto** [comment]
@bestpika 

>  I find that changing <app> to <div id="app"> breaks the whole layout of the site,

It is your CSS styling problem, not this library's problem.
DO NOT post your own problem here.

**Comment by bestpika** [comment]
@jsakamoto Okay.
However, Blazor's default element marker is `<app>`.
